### ISSUE TITLE
07-03_Primer_sample_CreateOfficeLayout.dyn can not work

### ISSUE THREAD

**Issue by KenLP** [DynamoDS/RefineryPrimer#10] opened 2019-07-01 19:55 UTC
## Situation right now

Cannot find the required Dynamo Package "AutodeskGD", so some nodes are unresolved.

## What improvement do you suggest ?

Could you please publish this package?

## How would this change improve the Primer ?
Understand this example

## Are you ready to write the content for this change ?

- [ ] Yes
- [x] No

**Comment by radumg** [comment] 2019-07-02 08:48
Hi Ken, thanks for writing in & taking interest in the primer and it’s examples.

As you may have noticed, the content is very much still undergoing changes, and a draft of the associated package is due to be published to the package manager in the next 2 weeks.

In the meantime, it would very helpful for us if you could answer a few short questions, in the spirit of making it easier & more useful to others too ?
- how did you discover the primer ?
- are there any parts you found that need clarifications or further explanations & examples ?
- what kind of workflows do you have in mind after reading the primer ?

Thanks in advance,
Radu

**Comment by SHKnudsen** [comment] 2019-07-02 09:46
@KenLP the nodes you are looking for has been moved to the SpacePlanning package in the RefineryToolkits (https://github.com/DynamoDS/RefineryToolkits/releases). I updated the workflow to use the nodes from that package, so please download the package and the workflow again and you should be good to go.

As @radumg mentioned all of this is still undergoing changes, but you should be fine to play around with it, just keep an eye out for new updates and releases.

**Comment by radumg** [comment] 2019-07-08 12:55
duplicate of #13

**Closed** 2019-07-08 12:54 UTC
